replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"

service:
  port: 8080

secret:
  name: metrics-app-secret
  envKey: PASSWORD

# ────────────────────────────────────────────────────────────────────────────
# Add this block so your serviceaccount.yaml template has something to read
serviceAccount:
  create: true          # Helm will render and create the ServiceAccount
  name: ""              # leave blank to let Helm name it; or set to an existing SA
  annotations: {}       # optional

# ────────────────────────────────────────────────────────────────────────────
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/affinity: "cookie"
  hosts:
    - host: localhost
      paths:
        - path: /counter
          pathType: Prefix

autoscaling:
  enabled: false
  # if you want HPA later, enable and configure:
  # minReplicas: 1
  # maxReplicas: 5
  # targetCPUUtilizationPercentage: 80

