# … your existing values …
replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"

service:
  port: 8080

secret:
  name: metrics-app-secret
  envKey: PASSWORD

serviceAccount:
  create: true
  name: ""
  annotations: {}

# ────────────────────────────────────────────────────
# ' NEW: Ingress configuration for ArgoCD sync
ingress:
  enabled: true                    # turn on Ingress
  className: nginx                 # match your ingressClassName
  annotations:
    # no rewrite-target here—let the app see the real path
    nginx.ingress.kubernetes.io/affinity: "cookie"
  hosts:
    - host: localhost
      paths:
        - path: /counter          # this path goes to /counter in your app
          pathType: Prefix
        - path: /                 # this path goes to the dashboard (your "/" handler)
          pathType: Prefix

# ────────────────────────────────────────────────────
autoscaling:
  enabled: false

