# … existing values …
replicaCount: 1

image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"

service:
  port: 8080

secret:
  name: metrics-app-secret
  envKey: PASSWORD

# ────────────────────────────────────────────────────
# ServiceAccount configuration (Argo CD needs this)
serviceAccount:
  create: true
  name: ""
  annotations: {}

# ────────────────────────────────────────────────────
# Ingress block — this is what Argo CD will sync
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/affinity: "cookie"
  hosts:
    - host: localhost
      paths:
        - path: /counter
          pathType: Prefix
        - path: /
          pathType: Prefix

# ────────────────────────────────────────────────────
autoscaling:
  enabled: false

